es:
  host: '192.168.0.105'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  suggestion_key_format: 'suggestion.%s'

db:
  host: '192.168.0.101'
  port: 3306
  user: 'dev'
  password: 'password'
  name: 'municipality'

consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'delete.municipality.profilepicture'
  group_id: 'consumer-delete-media-group'

health:
  port: ':8000'
  shutdown_endpoint: '/api/v1/consumer_delete_media_health/shutdown'
  content_type: 'application/json'